// automatically generated by the FlatBuffers compiler, do not modify

/**
 * The possible types of things that can exist.
 */
export enum BodyType{
  HEADQUARTERS = 0,
  CARRIER = 1,
  LAUNCHER = 2,
  AMPLIFIER = 3,
  DESTABILIZER = 4,
  BOOSTER = 5
}

