// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BodyType } from '../../battlecode/schema/body-type';


/**
 * Metadata about all bodies of a particular type.
 */
export class BodyTypeMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):BodyTypeMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBodyTypeMetadata(bb:flatbuffers.ByteBuffer, obj?:BodyTypeMetadata):BodyTypeMetadata {
  return (obj || new BodyTypeMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBodyTypeMetadata(bb:flatbuffers.ByteBuffer, obj?:BodyTypeMetadata):BodyTypeMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BodyTypeMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():BodyType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : BodyType.HEADQUARTERS;
}

buildCostAd():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

buildCostMn():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

buildCostEx():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

actionCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

movementCooldown():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

health():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

actionRadiusSquared():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

visionRadiusSquared():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

bytecodeLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startBodyTypeMetadata(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addType(builder:flatbuffers.Builder, type:BodyType) {
  builder.addFieldInt8(0, type, BodyType.HEADQUARTERS);
}

static addBuildCostAd(builder:flatbuffers.Builder, buildCostAd:number) {
  builder.addFieldInt32(1, buildCostAd, 0);
}

static addBuildCostMn(builder:flatbuffers.Builder, buildCostMn:number) {
  builder.addFieldInt32(2, buildCostMn, 0);
}

static addBuildCostEx(builder:flatbuffers.Builder, buildCostEx:number) {
  builder.addFieldInt32(3, buildCostEx, 0);
}

static addActionCooldown(builder:flatbuffers.Builder, actionCooldown:number) {
  builder.addFieldInt32(4, actionCooldown, 0);
}

static addMovementCooldown(builder:flatbuffers.Builder, movementCooldown:number) {
  builder.addFieldInt32(5, movementCooldown, 0);
}

static addHealth(builder:flatbuffers.Builder, health:number) {
  builder.addFieldInt32(6, health, 0);
}

static addActionRadiusSquared(builder:flatbuffers.Builder, actionRadiusSquared:number) {
  builder.addFieldInt32(7, actionRadiusSquared, 0);
}

static addVisionRadiusSquared(builder:flatbuffers.Builder, visionRadiusSquared:number) {
  builder.addFieldInt32(8, visionRadiusSquared, 0);
}

static addBytecodeLimit(builder:flatbuffers.Builder, bytecodeLimit:number) {
  builder.addFieldInt32(9, bytecodeLimit, 0);
}

static endBodyTypeMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBodyTypeMetadata(builder:flatbuffers.Builder, type:BodyType, buildCostAd:number, buildCostMn:number, buildCostEx:number, actionCooldown:number, movementCooldown:number, health:number, actionRadiusSquared:number, visionRadiusSquared:number, bytecodeLimit:number):flatbuffers.Offset {
  BodyTypeMetadata.startBodyTypeMetadata(builder);
  BodyTypeMetadata.addType(builder, type);
  BodyTypeMetadata.addBuildCostAd(builder, buildCostAd);
  BodyTypeMetadata.addBuildCostMn(builder, buildCostMn);
  BodyTypeMetadata.addBuildCostEx(builder, buildCostEx);
  BodyTypeMetadata.addActionCooldown(builder, actionCooldown);
  BodyTypeMetadata.addMovementCooldown(builder, movementCooldown);
  BodyTypeMetadata.addHealth(builder, health);
  BodyTypeMetadata.addActionRadiusSquared(builder, actionRadiusSquared);
  BodyTypeMetadata.addVisionRadiusSquared(builder, visionRadiusSquared);
  BodyTypeMetadata.addBytecodeLimit(builder, bytecodeLimit);
  return BodyTypeMetadata.endBodyTypeMetadata(builder);
}
}
