// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GameplayConstants {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameplayConstants {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameplayConstants(bb:flatbuffers.ByteBuffer, obj?:GameplayConstants):GameplayConstants {
  return (obj || new GameplayConstants()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameplayConstants(bb:flatbuffers.ByteBuffer, obj?:GameplayConstants):GameplayConstants {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameplayConstants()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

setupPhaseLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

flagMinDistance():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

globalUpgradeRoundDelay():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

passiveResourceRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

robotBaseHealth():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

jailedRounds():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

visionRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

actionRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGameplayConstants(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addSetupPhaseLength(builder:flatbuffers.Builder, setupPhaseLength:number) {
  builder.addFieldInt32(0, setupPhaseLength, 0);
}

static addFlagMinDistance(builder:flatbuffers.Builder, flagMinDistance:number) {
  builder.addFieldInt32(1, flagMinDistance, 0);
}

static addGlobalUpgradeRoundDelay(builder:flatbuffers.Builder, globalUpgradeRoundDelay:number) {
  builder.addFieldInt32(2, globalUpgradeRoundDelay, 0);
}

static addPassiveResourceRate(builder:flatbuffers.Builder, passiveResourceRate:number) {
  builder.addFieldInt32(3, passiveResourceRate, 0);
}

static addRobotBaseHealth(builder:flatbuffers.Builder, robotBaseHealth:number) {
  builder.addFieldInt32(4, robotBaseHealth, 0);
}

static addJailedRounds(builder:flatbuffers.Builder, jailedRounds:number) {
  builder.addFieldInt32(5, jailedRounds, 0);
}

static addVisionRadius(builder:flatbuffers.Builder, visionRadius:number) {
  builder.addFieldInt32(6, visionRadius, 0);
}

static addActionRadius(builder:flatbuffers.Builder, actionRadius:number) {
  builder.addFieldInt32(7, actionRadius, 0);
}

static endGameplayConstants(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameplayConstants(builder:flatbuffers.Builder, setupPhaseLength:number, flagMinDistance:number, globalUpgradeRoundDelay:number, passiveResourceRate:number, robotBaseHealth:number, jailedRounds:number, visionRadius:number, actionRadius:number):flatbuffers.Offset {
  GameplayConstants.startGameplayConstants(builder);
  GameplayConstants.addSetupPhaseLength(builder, setupPhaseLength);
  GameplayConstants.addFlagMinDistance(builder, flagMinDistance);
  GameplayConstants.addGlobalUpgradeRoundDelay(builder, globalUpgradeRoundDelay);
  GameplayConstants.addPassiveResourceRate(builder, passiveResourceRate);
  GameplayConstants.addRobotBaseHealth(builder, robotBaseHealth);
  GameplayConstants.addJailedRounds(builder, jailedRounds);
  GameplayConstants.addVisionRadius(builder, visionRadius);
  GameplayConstants.addActionRadius(builder, actionRadius);
  return GameplayConstants.endGameplayConstants(builder);
}
}
