// automatically generated by the FlatBuffers compiler, do not modify

export enum WinType {
  CAPTURE = 0,
  MORE_FLAG_CAPTURES = 1,
  LEVEL_SUM = 2,
  MORE_BREAD = 3,
  COIN_FLIP = 4,
  RESIGNATION = 5
}
