"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Action = void 0;
var Action;
(function (Action) {
    Action[Action["ATTACK"] = 0] = "ATTACK";
    Action[Action["HEAL"] = 1] = "HEAL";
    Action[Action["DIG"] = 2] = "DIG";
    Action[Action["FILL"] = 3] = "FILL";
    Action[Action["EXPLOSIVE_TRAP"] = 4] = "EXPLOSIVE_TRAP";
    Action[Action["WATER_TRAP"] = 5] = "WATER_TRAP";
    Action[Action["STUN_TRAP"] = 6] = "STUN_TRAP";
    Action[Action["PICKUP_FLAG"] = 7] = "PICKUP_FLAG";
    Action[Action["PLACE_FLAG"] = 8] = "PLACE_FLAG";
    Action[Action["CAPTURE_FLAG"] = 9] = "CAPTURE_FLAG";
    Action[Action["GLOBAL_UPGRADE"] = 10] = "GLOBAL_UPGRADE";
    /**
     * Dies due to an uncaught exception
     * Target: none
     */
    Action[Action["DIE_EXCEPTION"] = 11] = "DIE_EXCEPTION";
})(Action || (exports.Action = Action = {}));
