"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.GameFooter = void 0;
var flatbuffers = require("flatbuffers");
/**
 * The final event sent in the game.
 */
var GameFooter = /** @class */ (function () {
    function GameFooter() {
        this.bb = null;
        this.bb_pos = 0;
    }
    GameFooter.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    GameFooter.getRootAsGameFooter = function (bb, obj) {
        return (obj || new GameFooter()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    GameFooter.getSizePrefixedRootAsGameFooter = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new GameFooter()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    /**
     * The ID of the winning team of the game.
     */
    GameFooter.prototype.winner = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
    };
    GameFooter.startGameFooter = function (builder) {
        builder.startObject(1);
    };
    GameFooter.addWinner = function (builder, winner) {
        builder.addFieldInt8(0, winner, 0);
    };
    GameFooter.endGameFooter = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    GameFooter.createGameFooter = function (builder, winner) {
        GameFooter.startGameFooter(builder);
        GameFooter.addWinner(builder, winner);
        return GameFooter.endGameFooter(builder);
    };
    return GameFooter;
}());
exports.GameFooter = GameFooter;
