"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.SepcializationType = void 0;
var SepcializationType;
(function (SepcializationType) {
    SepcializationType[SepcializationType["ATTACK"] = 0] = "ATTACK";
    SepcializationType[SepcializationType["BUILD"] = 1] = "BUILD";
    SepcializationType[SepcializationType["HEAL"] = 2] = "HEAL";
})(SepcializationType = exports.SepcializationType || (exports.SepcializationType = {}));
