"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Vec = void 0;
var Vec = /** @class */ (function () {
    function Vec() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Vec.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Vec.prototype.x = function () {
        return this.bb.readInt32(this.bb_pos);
    };
    Vec.prototype.y = function () {
        return this.bb.readInt32(this.bb_pos + 4);
    };
    Vec.sizeOf = function () {
        return 8;
    };
    Vec.createVec = function (builder, x, y) {
        builder.prep(4, 8);
        builder.writeInt32(y);
        builder.writeInt32(x);
        return builder.offset();
    };
    return Vec;
}());
exports.Vec = Vec;
