"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.WinType = void 0;
var WinType;
(function (WinType) {
    WinType[WinType["CAPTURE"] = 0] = "CAPTURE";
    WinType[WinType["MORE_FLAG_CAPTURES"] = 1] = "MORE_FLAG_CAPTURES";
    WinType[WinType["LEVEL_SUM"] = 2] = "LEVEL_SUM";
    WinType[WinType["MORE_BREAD"] = 3] = "MORE_BREAD";
    WinType[WinType["COIN_FLIP"] = 4] = "COIN_FLIP";
    WinType[WinType["RESIGNATION"] = 5] = "RESIGNATION";
})(WinType || (exports.WinType = WinType = {}));
