// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * The possible types of things that can exist.
 */
public final class BodyType {
  private BodyType() { }
  public static final byte HEADQUARTERS = 0;
  public static final byte CARRIER = 1;
  public static final byte LAUNCHER = 2;
  public static final byte AMPLIFIER = 3;
  public static final byte DESTABILIZER = 4;
  public static final byte BOOSTER = 5;

  public static final String[] names = { "HEADQUARTERS", "CARRIER", "LAUNCHER", "AMPLIFIER", "DESTABILIZER", "BOOSTER", };

  public static String name(int e) { return names[e]; }
}

