// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class BuildActionType {
  private BuildActionType() { }
  public static final byte EXPLOSIVE_TRAP = 0;
  public static final byte WATER_TRAP = 1;
  public static final byte STUN_TRAP = 2;
  public static final byte DIG = 3;
  public static final byte FILL = 4;

  public static final String[] names = { "EXPLOSIVE_TRAP", "WATER_TRAP", "STUN_TRAP", "DIG", "FILL", };

  public static String name(int e) { return names[e]; }
}

