// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class GlobalUpgradeType {
  private GlobalUpgradeType() { }
  public static final byte ACTION_UPGRADE = 0;
  public static final byte HEALING_UPGRADE = 1;
  public static final byte CAPTURING_UPGRADE = 2;

  public static final String[] names = { "ACTION_UPGRADE", "HEALING_UPGRADE", "CAPTURING_UPGRADE", };

  public static String name(int e) { return names[e]; }
}

