// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class SepcializationType {
  private SepcializationType() { }
  public static final byte ATTACK = 0;
  public static final byte BUILD = 1;
  public static final byte HEAL = 2;

  public static final String[] names = { "ATTACK", "BUILD", "HEAL", };

  public static String name(int e) { return names[e]; }
}

