// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class WinType {
  private WinType() { }
  public static final byte CAPTURE = 0;
  public static final byte MORE_FLAG_CAPTURES = 1;
  public static final byte LEVEL_SUM = 2;
  public static final byte MORE_BREAD = 3;
  public static final byte COIN_FLIP = 4;
  public static final byte RESIGNATION = 5;

  public static final String[] names = { "CAPTURE", "MORE_FLAG_CAPTURES", "LEVEL_SUM", "MORE_BREAD", "COIN_FLIP", "RESIGNATION", };

  public static String name(int e) { return names[e]; }
}

