// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte ATTACK = 0;
  public static final byte HEAL = 1;
  public static final byte DIG = 2;
  public static final byte FILL = 3;
  public static final byte EXPLOSIVE_TRAP = 4;
  public static final byte WATER_TRAP = 5;
  public static final byte STUN_TRAP = 6;
  public static final byte PICKUP_FLAG = 7;
  public static final byte DROP_FLAG = 8;
  public static final byte CAPTURE_FLAG = 9;
  public static final byte RESET_FLAG = 10;
  public static final byte GLOBAL_UPGRADE = 11;
  /**
   * Dies due to an uncaught exception
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 12;

  public static final String[] names = { "ATTACK", "HEAL", "DIG", "FILL", "EXPLOSIVE_TRAP", "WATER_TRAP", "STUN_TRAP", "PICKUP_FLAG", "DROP_FLAG", "CAPTURE_FLAG", "RESET_FLAG", "GLOBAL_UPGRADE", "DIE_EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

