// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BuildActionMetadata extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BuildActionMetadata getRootAsBuildActionMetadata(ByteBuffer _bb) { return getRootAsBuildActionMetadata(_bb, new BuildActionMetadata()); }
  public static BuildActionMetadata getRootAsBuildActionMetadata(ByteBuffer _bb, BuildActionMetadata obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BuildActionMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int cost() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int buildCooldown() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createBuildActionMetadata(FlatBufferBuilder builder,
      byte type,
      int cost,
      int buildCooldown) {
    builder.startTable(3);
    BuildActionMetadata.addBuildCooldown(builder, buildCooldown);
    BuildActionMetadata.addCost(builder, cost);
    BuildActionMetadata.addType(builder, type);
    return BuildActionMetadata.endBuildActionMetadata(builder);
  }

  public static void startBuildActionMetadata(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addCost(FlatBufferBuilder builder, int cost) { builder.addInt(1, cost, 0); }
  public static void addBuildCooldown(FlatBufferBuilder builder, int buildCooldown) { builder.addInt(2, buildCooldown, 0); }
  public static int endBuildActionMetadata(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BuildActionMetadata get(int j) { return get(new BuildActionMetadata(), j); }
    public BuildActionMetadata get(BuildActionMetadata obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

