// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GlobalUpgradeMetadata extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GlobalUpgradeMetadata getRootAsGlobalUpgradeMetadata(ByteBuffer _bb) { return getRootAsGlobalUpgradeMetadata(_bb, new GlobalUpgradeMetadata()); }
  public static GlobalUpgradeMetadata getRootAsGlobalUpgradeMetadata(ByteBuffer _bb, GlobalUpgradeMetadata obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GlobalUpgradeMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int upgradeAmount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGlobalUpgradeMetadata(FlatBufferBuilder builder,
      byte type,
      int upgradeAmount) {
    builder.startTable(2);
    GlobalUpgradeMetadata.addUpgradeAmount(builder, upgradeAmount);
    GlobalUpgradeMetadata.addType(builder, type);
    return GlobalUpgradeMetadata.endGlobalUpgradeMetadata(builder);
  }

  public static void startGlobalUpgradeMetadata(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addUpgradeAmount(FlatBufferBuilder builder, int upgradeAmount) { builder.addInt(1, upgradeAmount, 0); }
  public static int endGlobalUpgradeMetadata(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GlobalUpgradeMetadata get(int j) { return get(new GlobalUpgradeMetadata(), j); }
    public GlobalUpgradeMetadata get(GlobalUpgradeMetadata obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

